import React, { useContext, useEffect, useState } from "react";
import Radio from "@mui/material/Radio";
import RadioGroup from "@mui/material/RadioGroup";
import FormControlLabel from "@mui/material/FormControlLabel";
import FormControl from "@mui/material/FormControl";
import FormLabel from "@mui/material/FormLabel";
import styles from "../../styles/ProfileSettings.module.sass";
import Head from "next/head";
import { useAuthCookie } from "../../hooks/useAuthCookie";
import { TextField } from "@mui/material";
import { AppContext } from "../../components/Layout/Layout";

export default function profileSettings() {
  // const [userData, setUserData] = useState();
  const { dataUser } = useAuthCookie();
  // const [color, setColor] = useState();
  const { webColor, setWebColor } = useContext(AppContext);

  const radioSubmit = () => {};
  const radioChange = (e) => {
    setWebColor(e.target.value);
  };

  return (
    <header className={styles.container}>
      <Head>
        <title>settings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.settings}>Настройки Аккаунта</h1>
      <FormControl component={"form"} onSubmit={radioSubmit}>
        <FormLabel id={styles.demoRowRadioButtonsGroupLabel}>
          Тема Сайта
        </FormLabel>
        <RadioGroup
          row
          aria-labelledby="demo-row-radio-buttons-group-label"
          defaultValue={webColor}
          name="row-radio-buttons-group"
        >
          <FormControlLabel
            value="white"
            name="webColor"
            onChange={radioChange}
            control={<Radio />}
            label="Белый"
          />
          <FormControlLabel
            value="black"
            name="webColor"
            onChange={radioChange}
            control={<Radio />}
            label="Черный"
          />
        </RadioGroup>
      </FormControl>
      <FormControl>
        <FormLabel id={styles.demoRowRadioButtonsGroupLabel}>
          Язык Сайта
        </FormLabel>
        <RadioGroup
          row
          aria-labelledby="demo-row-radio-buttons-group-label"
          defaultValue="Russian"
          name="row-radio-buttons-group"
        >
          <FormControlLabel
            value="Russian"
            control={<Radio />}
            label="Русский"
          />
          <FormControlLabel
            value="English"
            control={<Radio />}
            label="Английский"
          />
          <FormControlLabel
            value="Kyrgyz"
            control={<Radio />}
            label="Кыргызский"
          />
        </RadioGroup>
      </FormControl>
      <div className={styles.userLoginUpdate}>
        <h2 className={styles.userUpdate}>Аккаунт</h2>
        <div className={styles.userData}>
          <span>Логин:</span>
          <TextField
            id="standard-read-only-input"
            label="Логин"
            value={dataUser?.login}
            InputProps={{
              readOnly: true,
            }}
            variant="standard"
          />
          <span>Почта:</span>
          <TextField
            id="standard-read-only-input"
            label="Почта"
            value={dataUser?.email}
            InputProps={{
              readOnly: true,
            }}
            variant="standard"
          />
          <span>Имя:</span>
          <TextField
            id="standard-read-only-input"
            label="Имя"
            value={dataUser?.username + " " + dataUser?.lastName}
            InputProps={{
              readOnly: true,
            }}
            variant="standard"
          />
        </div>
      </div>
      <style jsx>{`
        body {
          backround-color: black;
        }
      `}</style>
    </header>
  );
}
