import * as React from "react";
import Radio from "@mui/material/Radio";
import RadioGroup from "@mui/material/RadioGroup";
import FormControlLabel from "@mui/material/FormControlLabel";
import FormControl from "@mui/material/FormControl";
import FormLabel from "@mui/material/FormLabel";
import styles from "../../styles/ProfileSettings.module.sass";
import Head from "next/head";
import { useAuthCookie } from "../../hooks/useAuthCookie";

export default function profileSettings() {
  const { dataUser, setDataUser } = useAuthCookie();

  return (
    <header className={styles.container}>
      <Head>
        <title>settings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.settings}>Настройки Аккаунта</h1>
      <FormControl>
        <FormLabel id={styles.demoRowRadioButtonsGroupLabel}>
          Тема Сайта
        </FormLabel>
        <RadioGroup
          row
          aria-labelledby="demo-row-radio-buttons-group-label"
          defaultValue="White"
          name="row-radio-buttons-group"
        >
          <FormControlLabel value="White" control={<Radio />} label="Белый" />
          <FormControlLabel value="Black" control={<Radio />} label="Черный" />
        </RadioGroup>
      </FormControl>
      <FormControl>
        <FormLabel id={styles.demoRowRadioButtonsGroupLabel}>
          Язык Сайта
        </FormLabel>
        <RadioGroup
          row
          aria-labelledby="demo-row-radio-buttons-group-label"
          defaultValue="Russian"
          name="row-radio-buttons-group"
        >
          <FormControlLabel
            value="Russian"
            control={<Radio />}
            label="Русский"
          />
          <FormControlLabel
            value="English"
            control={<Radio />}
            label="Английский"
          />
          <FormControlLabel
            value="Kyrgyz"
            control={<Radio />}
            label="Кыргызский"
          />
        </RadioGroup>
      </FormControl>
      <div className={styles.userLoginUpdate}>
        <h2 className={styles.userUpdate}>Аккаунт</h2>
        {/* {dataUser.map((item) => {
          console.log(item);
        })} */}
      </div>
    </header>
  );
}
