import style from "./AddNews.module.sass";
import Head from "next/head";
import FormInput from "../../components/UI/FormInput/FormInput";
import axios from "../../api/axios.news";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { useAuthCookie } from "../../hooks/useAuthCookie";

function addNews({ data }) {
  const router = useRouter();

  // const { dataUser } = useAuthCookie();
  // if (!dataUser) { 
  //   return <createUserLogin />
  // }
  return (
    <section className="container">
      <Head>
        <title>addNews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={style.mainHeader}>
        <h1 className={style.mainTitle}>Добавить Новость</h1>
        <FormInput data={data} />
      </header>
    </section>
  );
}
export default addNews;

export const getStaticProps = async () => {
  try {
    const res = await axios.get("/categories");
    if (!res.data) {
      throw new Error();
    }
    return {
      props: {
        data: res?.data?.data,
      },
    };
  } catch (error) {
    return {
      props: {
        data: [],
        error,
      },
    };
  }
};
